databases:
  - name: tasks-database  # Nombre de la base de datos en Render
    plan: free
    databaseName: tasks_db  # Nombre interno de la base de datos
    user: tasks_user  # Usuario de la base de datos

services:
  - type: web
    plan: free
    name: tasks-app  # Nombre del servicio en Render
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn CRUD_tasklist.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tasks-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "tasks-app.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "TASKS_LIST_CRUD_DJANGO.settings"
